name: CI

on: [pull_request, push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: extract branch name on push event
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV; echo "HASH=${GITHUB_SHA::6}" >> $GITHUB_ENV; uname -m

      - name: extract branch name on PR event
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV; echo "HASH=${GITHUB_SHA::6}" >> $GITHUB_ENV;

      - name: Get branch name
        run: echo 'The branch name is' ${{ env.BRANCH }}; echo 'HASH is' ${{ env.HASH }}

      - name: checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./services/pingpong
          file: ./services/pingpong/Dockerfile.multistage
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/esgbook:${{ env.BRANCH }}-${{ env.HASH }}
          